"""Encryption at rest for the stored Gmail refresh token (Fernet: AES-128-CBC + HMAC-SHA256).

The key comes ONLY from the OAUTH_ENCRYPTION_KEY setting (generated by `python -m app.gmail.keygen`). Each stored token keeps the
fingerprint of the key that encrypted it, so a changed or lost key is reported as "reconnect", never as a crash or garbage.
No message in this module ever contains a key or a token.
"""
import hashlib

from cryptography.fernet import Fernet, InvalidToken

from app.config import Settings


class GmailCryptoError(Exception):
    def __init__(self, message: str):
        super().__init__(message)
        self.message = message


class KeyMissing(GmailCryptoError):
    """OAUTH_ENCRYPTION_KEY is not set."""


class KeyInvalid(GmailCryptoError):
    """OAUTH_ENCRYPTION_KEY is set but is not a Fernet key."""


class KeyMismatch(GmailCryptoError):
    """The stored token was encrypted with a different key."""


class TokenUnreadable(GmailCryptoError):
    """The stored token does not decrypt with the current key (tampered or corrupt)."""


def fingerprint(key: str) -> str:
    """Identifies a key without revealing it (16 hex characters of its SHA-256)."""
    return hashlib.sha256(key.encode("ascii")).hexdigest()[:16]


class TokenCipher:
    def __init__(self, key: str):
        try:
            self._fernet = Fernet(key.encode("ascii"))
        except (ValueError, TypeError, UnicodeEncodeError):
            raise KeyInvalid("OAUTH_ENCRYPTION_KEY is not a valid key. Generate one with: python -m app.gmail.keygen") from None
        self.fingerprint = fingerprint(key)

    @classmethod
    def from_settings(cls, settings: Settings) -> "TokenCipher":
        key = settings.oauth_encryption_key_value()
        if key is None:
            raise KeyMissing("OAUTH_ENCRYPTION_KEY is not set. Generate one with: python -m app.gmail.keygen --append-env")
        return cls(key)

    def encrypt(self, plaintext: str) -> bytes:
        return self._fernet.encrypt(plaintext.encode("utf-8"))

    def decrypt(self, token: bytes, key_fingerprint: str) -> str:
        if key_fingerprint != self.fingerprint:
            raise KeyMismatch("The stored Gmail credential was encrypted with a different OAUTH_ENCRYPTION_KEY; connect Gmail again.")
        try:
            return self._fernet.decrypt(bytes(token)).decode("utf-8")
        except (InvalidToken, UnicodeDecodeError):
            raise TokenUnreadable("The stored Gmail credential cannot be decrypted; connect Gmail again.") from None
